name: Bug Report
description: Report a bug or unexpected behavior
title: "[Bug]: "
labels: ["bug"]
assignees:
  - dboncioaga

body:
  - type: markdown
    attributes:
      value: |
        Thanks for taking the time to report a bug! Please fill out the form below.

  - type: textarea
    id: description
    attributes:
      label: Bug Description
      description: A clear and concise description of what the bug is.
      placeholder: Tell us what you see!
    validations:
      required: true

  - type: textarea
    id: steps
    attributes:
      label: Steps to Reproduce
      description: Steps to reproduce the behavior
      placeholder: |
        1. Create a validator with '...'
        2. Call validate() with '...'
        3. See error
    validations:
      required: true

  - type: textarea
    id: expected
    attributes:
      label: Expected Behavior
      description: What you expected to happen
      placeholder: The validator should return...
    validations:
      required: true

  - type: textarea
    id: actual
    attributes:
      label: Actual Behavior
      description: What actually happened
      placeholder: The validator throws...
    validations:
      required: true

  - type: textarea
    id: code
    attributes:
      label: Code Sample
      description: If applicable, add a minimal code sample to reproduce the issue
      render: java
      placeholder: |
        CuiValidator validator = new DefaultCuiValidator();
        ValidationResult result = validator.validate("12345678");

  - type: input
    id: version
    attributes:
      label: cui4j Version
      description: Which version of cui4j are you using?
      placeholder: "0.1.0"
    validations:
      required: true

  - type: input
    id: java-version
    attributes:
      label: Java Version
      description: Which Java version are you using?
      placeholder: "25"
    validations:
      required: true

  - type: input
    id: spring-boot-version
    attributes:
      label: Spring Boot Version (if applicable)
      description: Which Spring Boot version are you using?
      placeholder: "4.0.1"
    validations:
      required: false

  - type: textarea
    id: environment
    attributes:
      label: Environment
      description: Additional environment details
      placeholder: |
        OS: macOS 15.0
        Build Tool: Maven 3.9.9
        IDE: IntelliJ IDEA 2026.1

  - type: textarea
    id: additional
    attributes:
      label: Additional Context
      description: Add any other context about the problem here
      placeholder: This started happening after...
